extends Node

# Groups
const PLAYER_GROUP = "player"

# Elements
const ELEMENT_NONE = "none"
const ELEMENT_FIRE = "fire"
const ELEMENT_WATER = "water"
const ELEMENT_EARTH = "earth"
const ELEMENT_LIGHTNING = "lightning"
const ELEMENT_WIND = "wind"
const ELEMENT_DURATION = 120.0
const FIRE_DAMAGE = 1
const FIRE_DURATION = 5.0
const WATER_DAMAGE = 3
const EARTH_DAMAGE = 3
const EARTH_DURATION = 3.0
const WIND_FREEZE_DURATION = 5
const LIGHTNING_DAMAGE = 5
const RESISTANCE_MULTIPLIER = 0.3
const EFFECTIVENESS_MULTIPLIER = 2.0
# Weapons
const WEAPON_GLOCK = "glock"
const WEAPON_SHOTGUN = "shotgun"
const WEAPON_MACHINE = "machine"
const GLOCK_FIRE_RATE = 0.6
const GLOCK_DAMAGE = 4
const SHOTGUN_FIRE_RATE = 0.9
const SHOTGUN_DAMAGE = 5
const MACHINE_FIRE_RATE = 0.1
const MACHINE_DAMAGE = 3

# Player
const STARTING_HEALTH = 100
const STARTING_STAMINA = 100
const STARTING_CONTINUES = 10
const PLAYER_SPEED = 250
const CONTINUE_SPEED_LOSS = 10
const CONTINUE_FIRE_RATE_INCREASE = 0.05
const STAMINA_DRAIN = 10
const STAMINA_RECOVERY = 15

# Enemy
const DAMAGE_INTERVAL = 3.0
const BULLET_LIFETIME = 3.0
const STARTING_ENEMIES = 5
const ENEMY_PER_ROUND = 5
const ENEMY_SPAWN_DELAY = 1
const ROUND_HEALTH_INCREASE = 1	
const ELEMENT_FIRE_COLOR = Color(1, 0.2, 0.1)
const ELEMENT_WATER_COLOR = Color(0.2, 0.5, 1)
const ELEMENT_EARTH_COLOR = Color(0.6, 0.4, 0.2)
const ELEMENT_LIGHTNING_COLOR = Color(1, 1, 0.2)
const ELEMENT_WIND_COLOR = Color(0.3, 1, 0.5)
const ELEMENT_NONE_COLOR = Color(1, 1, 1)
# Boss

const BOSS_ROUND_INTERVAL = 5	
const ROUND_UNLOCK_SHOTGUN = 10
const ROUND_UNLOCK_MACHINE = 20
